---
  swagger: "2.0"
  info:
    version: "1.2.0"
    title: "SFMOHD API"
    description:  |
      The first version of the SFMO Housing API is an exciting step in providing information to listings to apply.  We want to make it easy for you, to build apps and have open access to city Listing data to apply for affordable housing

      There are two ways to connect to the api-
      The listing data is public domain and can be accessed at <publicsite>/salesforce.com/apexrest
      You can connect your listing information to this

      To connect a full fledge application to the city data in order to facilitate applications please email the city, and we will get you the proper credentials.
      All application data requires oauth to connect.


  host: "salesforce.com"
  schemes:
    - "https"
  basePath: "/services/apexrest"
  securityDefinitions:
    restrictedAccess:
      type: oauth2
      flow: password
      tokenUrl: https://test.salesforce.com/services/oauth2/token
      scopes:
        Listing: |
          Information of a particular listing, including qualifications, to apply for listing as well as details on the listing itself - this is available via public and pwd based oauth
        ListingDetails: |
          Listing information coupled with detailed information on unit summary data, and if a criteria was passed in the request, it will show the "match" on the citeria
        UnitSummary: summary information on particular unit types for a listing
        ShortForm: the shortform application for a particular person for a particular listing this includes contact/household information for a person
        LotteryMember: current lottery memebers for a given listing
        
        Person: primary applicant/person who will have applications connected to them.  

        ami: ami calculation
    public:
      type: apiKey
      in: query
      name: access_token

  security:
    - restrictedAccess:
      - Listing
      - ListingDetails
      - LotteryMember
      - UnitSummary
      - ShortForm
      - Person
      - ami

    - public: []


  paths:
   
    
    /Listing/{sfdcid}:
      get:

        description: "This returns the Listing information and its summary information."
        tags:
          - "Listing"
    /Listing:
      get:
        description: "This returns the Listing information and its summary information."
        tags:
          - "Listing"
    /Listing/LotteryResult/Summary/{listingID}:
      get:
        description: "This returns the LotteryResult"
        deprecated: true
        tags:
          - "Listing"
    /Listing/LotteryResult/Bucket/{listingID}:
      get:
        description: "this returns the bucket of lottery results, application results are empty
            the bucket of results is a list of applicaition results by preference - we may need to add additional filter parameters to define result set size - default is to return top 100"
        tags:
          - "Listing"
        deprecated: true
    /Listing/LotteryResult/{listingID}/{lotteryNumber}:
      get:
        description: "This returns the Listing result - with 1 applicationResult inside this is the Application with the appropriate lottery number.  If no lotteryNumber fits, applicationsResult will be empty.  If listing isIncorrect it will error."
        tags:
          - "Listing"
    /Listing/LotteryResult/{listingID}:
      get:
        description: "This returns the Listing result - with 1 applicationResult inside this is the Application with the appropriate lottery number.  If no lotteryNumber fits, applicationsResult will be empty.  If listing isIncorrect it will error."
        tags:
          - "Listing"
    /ListingDetails/{sfdcid}:
      get:
        description: "This returns the Listing information and its summary information."
        tags:
          - "Listing"
    /ListingDetails:
      get:
        description: "This returns the Listing information and its summary information."
        tags:
          - "Listing"
    /ListingDetails/Criteria/:
      get:
        description: "This queries the Listing information and its summary information."
        tags:
          - "Listing"
    /Listing/EligibilityCheck:
      get:
        description: "This returns the Listing Id and eligibility information."
        tags:
          - "Listing"
    /Listing/Units/{id}':
      get:
        description: "returns Units for listing based on Listing ID"
        tags:
          - "Listing"
    /Listing/Units/':
      get:
        description: "returns Units for listing based on Listing ID"
        tags:
          - "Listing"
    /LotteryPreference/{id}':
      get:
        deprecated: true
        description: "returns lottery Preference by ID"
        tags:
          - "Listing"
          - "Shortform Application"
    /LotteryPreference/':
      get:
        deprecated: true
        description: "returns lottery preferences by ID.  If not id is provided it returns all lottery preferences"
        tags:
          - "Listing"
          - "Shortform Application"
    /Listing/UnitSummary/{id}':
      get:
        description: "returns UnitSummary for listings by unit type"
        tags:
          - "Listing"
    /Listing/Preferences/{listingID}':
      get:
        description: "returns UnitSummary for listings by unit type"
        tags:
          - "Listing"
    /Listing/UnitSummary/':
      get:
        description: "returns UnitSummary for listings by unit type"
        tags:
          - "Listing"


    /ami:
      get:
        description: "Returns the ami table value based on 2 passed in parameters"
        tags:
          - "AMI"
    /ami/calc/:
      get:
        description: "Calculates the percentage ami based off household and amount and returns ami"
        tags:
          - "AMI"
    /ami/charts/:
      get:
        description: "returns the list of application charts type and years for those chart types"

        tags:
          - "AMI"
    /LotteryMember/{id}':
      get:
        security:
          - restrictedAccess:
            - LotteryMember
            - Listing
        description: "returns lottery members by listing id"
        tags:
          - "Listing"
          - "Shortform Application"
    /LotteryMember/':
      get:
        security:
          - restrictedAccess:
            - LotteryMember
            - Listing

        description: "returns lottery Members for listing - either id or ids is required"
        tags:
          - "Listing"
          - "Shortform Application"
    /Person/{sfdcid}:
      get:

        description: "This returns a Perons account data.  This is their contact information"
        tags:
          - "Person"
    /Person/:
      post:
        security:
          - restrictedAccess:
            - Person
        tags:
          - "Person/Account Management"

    /shortForm/list/{ContactID}:
      get:
        security:
          - restrictedAccess:
            - ShortForm
        description: "This returns the Listing information and its summary information."
        tags:
          - "Shortform Application"

    /shortForm/{shortFormId}:
      get:
        security:
          - restrictedAccess:
            - ShortForm
        description: "This returns the Listing information and its summary information."
        tags:
          - "Shortform Application"
    /shortForm/:
      put:
        security:
          - restrictedAccess:
            - ShortForm
        tags:
          - "Shortform Application"

    /shortForm/delete/{shortFormId}:
      delete:
        security:
          - restrictedAccess:
            - ShortForm
        description: deletes specified application
        tags:
           - "Shortform Application"
    /shortForm/file/{shortFormId}:
      post:
        security:
          - restrictedAccess:
            - ShortForm
        description: upload attachment to shortform.
        tags:
           - "Shortform Application"
    /shortForm/contact/delete:
      delete:
        security:
          - restrictedAccess:
            - ShortForm
        description: deletes specified contact from household  - use "delete" instead
        tags:
          - "Shortform Application"