// *****************************************************************************
// CLASS: HOP_DuplicateApplicationsController
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Controller class for the HOP_DuplicateApplications page.
//
// *****************************************************************************

public without sharing class HOP_DuplicateApplicationsController extends HOP_ControllerBase {

	public HOP_DuplicateApplicationsController() {
		// The current User license name (logic inherited from HOP_ControllerBase)
		// is used on the page to control what Salesforce DataTables displays.
		super();
	}

}