// *****************************************************************************
// CLASS: HOP_FlaggedApplicationsController
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Controller class for the HOP_FlaggedApplications page.
//
// *****************************************************************************

public without sharing class HOP_FlaggedApplicationsController extends HOP_ControllerBase {

	public HOP_FlaggedApplicationsController() {
		// The current User license name (logic inherited from HOP_ControllerBase)
		// is used on the page to control what Salesforce DataTables displays.
		super();
	}

}