// *****************************************************************************
// CLASS: HOP_TemplateControllerTest
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Test class for the HOP_TemplateController class.
//
// *****************************************************************************

@isTest
private class HOP_TemplateControllerTest {
	
	@isTest
	static void HOP_TemplateControllerTest() {
		HOP_TemplateController tc = new HOP_TemplateController();
	}
	
}