// *****************************************************************************
// CLASS: HOP_ListingsController
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Controller class for the HOP_Listings page.
//
// *****************************************************************************

public without sharing class HOP_ListingsController extends HOP_ControllerBase {

	public HOP_ListingsController() {
		super();
	}

}