// *****************************************************************************
// CLASS: HOP_Constants
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 03/08/16
// Description: Class that holds all of the HOP global constants.
//
// *****************************************************************************

public without sharing class HOP_Constants {

	public static final String COMMUNITY_LICENSE_NAME = 'Customer Community Login';
	public static final String DRAFT_APPLICATION = 'Draft';
	public static final String PAPER_APPLICATION = 'Paper';
	
	public static final String ERROR_ID_OR_LISTINGID = 'You must specify either an id or a listingId URL parameter';
	public static final String ERROR_APPLICATION_NOT_FOUND = 'Application record with provided Id was not found';
	public static final String ERROR_LISTING_COMPLETE = 'The Lottery is already Complete, you cannot edit this Application';
	public static final String ERROR_NO_ACCESS = 'You do not have permission to access this';
	public static final String ERROR_LISTING_NOT_FOUND = 'Listing record with provided Id was not found';
	public static final String ERROR_ID_NOT_PROVIDED = 'id URL parameter was not provided';
	public static final String ERROR_FLAGGED_RECORD_SET_NOT_FOUND = 'Flagged Record Set with provided Id was not found';

}