// *****************************************************************************
// CLASS: HOP_TemplateController
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Controller class for the HOP_Template page.
//
// *****************************************************************************

public class HOP_TemplateController {

    public HOP_TemplateController() {
        // Sets the headers for IE, don't remove;
        Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=Edge');
    }

}