// *****************************************************************************
// CLASS: HOP_ApplicationsController
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Controller class for the HOP_Applications page.
//
// *****************************************************************************

public without sharing class HOP_ApplicationsController extends HOP_ControllerBase {

	public HOP_ApplicationsController() {
		// The current User license name (logic inherited from HOP_ControllerBase)
		// is used on the page to control what Salesforce DataTables displays.
		super();
	}

}